### ISSUE TITLE
[question] retrieving records from a '3rd party system'

### ISSUE THREAD

**Issue by Licenser** [aetrion/erl-dns#39]
Hi,
I've been digging through the code and examples  and have a question I still came up bank with. Let me start with what I try to achive:

I am writing a cloud orchestration system (https://github.com/project-fifo) and I currently am trying to allow DNS queries that dynamically resolve to machines created in FiFo. so basically the logic I'm looking for is in pseudo code:

```
if cahced(query)
then
  cached_reply()
else
  if lookup_in_fifo()
  then
    cache_loopup(),
    reply_result()
  else
     not_found()
  end
end
```

I've tried to put in a custom handler but I don't find the logic of when those handlers (like the example handler) is called, it seems that a zone entry needs to exist in some way for it even to be called. 

So far I've found out that:
- a zone file needs to exist with a SOA record so the query isn't shut down right away
- the query for a non existing record goes to the `erldns_resolver` and ends up in `resolve_best_match_referral` never reaching the custom handlers.

the zone file I tried it with is:

``` json
[
    {
        "name": "fifo.cloud",
        "records": [
            {
                "name": "fifo.cloud",
                "type": "SOA",
                "ttl": 3600,
                "data": {
                    "mname": "ns1.fifo.cloud",
                    "rname": "admin.fifo.cloud",
                    "serial": 2013022001,
                    "refresh": 86400,
                    "retry": 7200,
                    "expire": 604800,
                    "minimum": 300
                }
            },
            {
                "name": "fifo.cloud",
                "type": "A",
                "ttl": 3600,
                "data": {
                    "ip": "1.2.3.4"
                }
            },
            {
                "name": "fifo.cloud",
                "type": "AAAA",
                "ttl": 3600,
                "data": {
                    "ip": "2001:6A8:0:1:210:4BFF:FE4B:4C61"
                }
            },
            {
                "name": "fifo.cloud",
                "type": "NS",
                "ttl": 3600,
                "data": {
                    "dname": "ns1.fifo.cloud"
                }
            }
        ]
    }
]
```

and the query I ran is something like:

`dig -p8053 @127.0.0.1 my-host.fifo.cloud  a`

**Comment by aeden** [comment]
A custom handler would only be useful if there is a custom type in the zone. For example, we use the custom handlers for ALIAS, URL and POOL record types at DNSimple.

I think what you will likely need to do is to write a specialized storage implementation. You can then register your storage implementation as shown in the example config: https://github.com/aetrion/erl-dns/blob/master/erldns.config.example#L4-L12

All zone lookups go through the zone cache, which delegates to the storage engine for actually looking up the zones and records: https://github.com/aetrion/erl-dns/blob/master/src/erldns_zone_cache.erl

**Comment by Licenser** [comment]
Hi thanks for the quick reply! I really appreciate that, I've looked into the storage implementation but it seems like it only loads data once at boot up and then keeps it cached instead of looking data up on the fly?

What I ended up doing in the short term is implementing a delegation handler [1] that if the cache and config files allows specifying a secondary call to `get_records_by_name/1` in a different module.

[1] https://github.com/project-fifo/erl-dns/pull/1

**Comment by aeden** [comment]
> Hi thanks for the quick reply! I really appreciate that, I've looked into the storage implementation but it seems like it only loads data once at boot up and then keeps it cached instead of looking data up on the fly?

It doesn't have to. You could implement the various read methods so they are dynamic. You need to be attentive to your performance requirements though and be aware that any sort of degradation in response from the on-the-fly data lookup could cause DNS lookups to timeout.

In our production systems we have another process which handles updating the zone in memory as changes arrive, which I've found works well to keep the throughput speeds optimal, but that might not work in your situation.

**Comment by Licenser** [comment]
Good advice! I think I'm trying to solve a much smaller problem then you guys, so the speed of a (approx.) riak-get will probably enough for the few dozens queries I'll have to serve.

I've looked at the storage backend today and it seems not to really fit what I try to achieve, it would require implement a lot more then 'needed'.

I'm happy to make a PR to add the delegate functionality I have in my branch but I am not sure if that really fits your goal for erl-dns. I can elaborate a bit on what exactly I did there and why, of if you think it's a bad fit feel free to just close this issue :)

I really appreciate the help and time you took to explain how things work!

**Comment by aeden** [comment]
Is it in your `master` or a branch? I can take a look and see if I understand and whether or not it makes sense in the core.

**Comment by Licenser** [comment]
my master is up to date with yours I created a PR against my own master to show the delta https://github.com/project-fifo/erl-dns/pull/1

**Comment by tsloughter** [comment]
Weird, I was about to open a ticket about this very issue :).

@Licenser you have a branch that allows for custom handler to be used without requiring an SOA record to exist for the zone first?

**Comment by tsloughter** [comment]
Or no... this still only happens after verifying the SOA record for the zone.

**Comment by Licenser** [comment]
Yap it still is after the SOA record, this is however intentional, I didn't want to replace 'the entire thing' just the source of where the records are provided, plus keep the ability to serve other data normally.

**Comment by tsloughter** [comment]
Damn, ok, I guess I'll write my own patch :)

To be clear about my "needs", I'm playing around writing a Consul clone to use for tutorials on stuff like releases, deployment, node clustering, etc.. There are multiple interfaces (DNS, HTTP, will have a straight Erlang interface too for this) to access the same data. So I don't want to have to have any real records in erldns, only to have the requests come in, be handed off to a custom handler which checks the common data store and creates the appropriate DNS records to return if they exist.

**Comment by Licenser** [comment]
That is pretty exactly what I'm doing, just that my source of truth is fifo's VM list not services registering. I found keeping the 1 SOA record entry not much of a hassle.

**Comment by tsloughter** [comment]
Hm, you might actually be right. Since the top level domain would be part of the configuration, and not dynamically input, it could simply be added when the app is started.

**Comment by Licenser** [comment]
Exactly, I still keep the .json formate since in my use case having to option to add additional records is a plus but it isn't dynamic it's configuration and in some place you need to configure the root domain of the DNS server, can as well include the SOA information there ;)

**Comment by tsloughter** [comment]
Cool. Now to convince them to merge your changes in and publish to hex ;)

**Comment by aeden** [comment]
Package the changes as pull request and assuming it is both clean and will not disrupt normal DNS operations, then I'll merge it in. We operate erldns is a highly-available production environment so I need to make sure any changes do not cause performance degradation or errors, that's all. :wink:

**Comment by aeden** [comment]
And to be clear, by clean I mean the smallest number of changes to accomplish what you need. If there are a bunch of unrelated changes it's harder for me to review and consider for inclusion in the core.

**Comment by Licenser** [comment]
deal! Thanks mate!

**Comment by aeden** [comment]
Closing this as answered.
