### ISSUE TITLE
Suppressed Error?

### ISSUE THREAD

**Issue by sargun** [aetrion/erl-dns#46]
I was looking at `erldns_zone_cache:put_zone` (https://github.com/aetrion/erl-dns/blob/master/src/erldns_zone_cache.erl#L189-L199), and it seems like the errors that come out of `erldns_storage` are suppressed. Is there a reason not to return the error code from the backend?

**Comment by aeden** [comment]
You are right, it would probably be better to return the result from the backend.

One note: different backends will need to normalize the results to facilitate pattern matching.

**Comment by aeden** [comment]
I realize my interpretation was off. I understand now the change that needs to be made and am preparing a PR.
