### ISSUE TITLE
Erl-DNS makes hosting TLDs problematic

### ISSUE THREAD

**Issue by sargun** [aetrion/erl-dns#48]
Here: https://github.com/aetrion/erl-dns/blob/master/src/erldns_zone_cache.erl#L91 -- if erl-dns is returning the authority for a TLD that it's hosting, it's problematic and it will return zone_not_found if it's hosting a single-level domain. Is there a reason for this, or can we get rid of it?

**Comment by aeden** [comment]
Go ahead and remove it.

**Comment by sargun** [comment]
PR: https://github.com/aetrion/erl-dns/pull/49

**Comment by aeden** [comment]
PR merged.
