### ISSUE TITLE
Compilation fails , please help me

### ISSUE THREAD

**Issue by basanta49** [aetrion/erl-dns#52]
Compiled src/erldns_packet_cache.erl
src/erldns_zone_parser.erl:139: referring to built-in type set as a remote type; please take out the module name
src/erldns_zone_parser.erl:139: referring to built-in type set as a remote type; please take out the module name
ERROR: compile failed while processing /home/basanta/dnsSoftware/erl-dns: rebar_abort

**Comment by aeden** [comment]
- What version of Erlang are you using?
- What command are you using to compile?

**Comment by aeden** [comment]
If you still need help compiling at some point, please reopen this issue with the answers to the questions above and I'll see if I can help troubleshoot.
